# Generated by Django 4.2.27 on 2025-12-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, verbose_name='疾病名称')),
                ('symptoms', models.TextField(verbose_name='症状描述')),
                ('affected_count', models.IntegerField(default=1, verbose_name='发病数量')),  # type: ignore
                ('report_date', models.DateField(verbose_name='上报日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('treating', '治疗中'), ('recovered', '已康复'), ('died', '死亡')], default='pending', max_length=20, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '疾病上报',
                'verbose_name_plural': '疾病上报',
                'db_table': 'production_disease',
            },
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=100, verbose_name='饲料名称')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前库存量')),
            ],
            options={
                'verbose_name': '饲料信息',
                'verbose_name_plural': '饲料信息',
                'db_table': 'production_feed',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='疫苗名称')),
                ('vaccination_date', models.DateField(verbose_name='接种日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='接种备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.livestockbatch', verbose_name='关联批次')),
            ],
            options={
                'verbose_name': '疫苗接种',
                'verbose_name_plural': '疫苗接种',
                'db_table': 'production_vaccine',
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投喂重量')),
                ('feeding_time', models.DateTimeField(verbose_name='投喂时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='livestock.livestockbatch', verbose_name='关联批次')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.feedinfo', verbose_name='关联饲料')),
            ],
            options={
                'verbose_name': '喂养记录',
                'verbose_name_plural': '喂养记录',
                'db_table': 'production_feeding',
            },
        ),
    ]
