# Generated by Django 4.2.27 on 2025-12-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('livestock', '0002_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='users.farmerprofile', verbose_name='所属养殖户'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='livestock.livestockbatch', verbose_name='关联批次'),
        ),
    ]
