# Generated by Django 4.2.27 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasereport',
            name='report_date',
            field=models.DateField(db_index=True, verbose_name='上报日期'),
        ),
    ]
