# Generated by Django 4.2.27 on 2025-12-29 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_diseasereport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间'),
        ),
    ]
