# Generated by Django 4.2.27 on 2025-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_feedinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库时间'),
        ),
    ]
