# Generated by Django 4.2.27 on 2025-12-29 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_feedinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='feeding_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投喂时间'),
        ),
    ]
