# Generated by Django 4.2.27 on 2025-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_feedingrecord_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='next_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次接种日期'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
