# Generated by Django 4.2.27 on 2025-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_vaccinationrecord_next_vaccination_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feeds/', verbose_name='饲料图片'),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='饲料简介'),
        ),
    ]
