# Generated by Django 4.2.27 on 2025-12-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_feedinfo_image_feedinfo_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinfo',
            name='unit',
        ),
    ]
