# Generated by Django 4.2.27 on 2025-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_feedinfo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinfo',
            name='unit',
            field=models.CharField(default='kg', max_length=20, verbose_name='计量单位'),
        ),
    ]
