# Generated by Django 4.2.27 on 2025-12-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_feedinfo_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='单位名称')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='换算系数(相对于公斤)')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认单位')),  # type: ignore
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统内置')),  # type: ignore
            ],
            options={
                'verbose_name': '单位换算配置',
                'verbose_name_plural': '单位换算配置',
                'db_table': 'production_unit_config',
            },
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='original_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='原始输入数量'),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='standard_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标准换算数量(公斤)'),
        ),
        migrations.AddField(
            model_name='feedinfo',
            name='unit_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='换算系数'),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前总库存(公斤)'),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='计量单位'),
        ),
    ]
