# Generated by Django 4.2.27 on 2025-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_unitconfig_feedinfo_original_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitConfig',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='standard_quantity',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='unit_factor',
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前库存量'),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='计量单位'),
        ),
    ]
