# Generated by Django 4.2.27 on 2025-12-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_delete_unitconfig_remove_feedinfo_original_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinfo',
            name='brand',
        ),
    ]
