# Generated by Django 4.2.27 on 2026-01-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_diseasereport_assigned_vet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasereport',
            name='assigned_vet',
        ),
    ]
