# Generated by Django 4.2.27 on 2026-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_diseasereport_assigned_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinfo',
            name='unit',
            field=models.CharField(default='kg', editable=False, max_length=50, verbose_name='计量单位'),
        ),
    ]
