# Generated by Django 4.2.27 on 2025-12-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('location_code', models.CharField(max_length=50, verbose_name='区域编号')),
                ('capacity', models.IntegerField(default=0, verbose_name='容纳规模')),  # type: ignore
                ('description', models.TextField(blank=True, null=True, verbose_name='区域描述')),
            ],
            options={
                'verbose_name': '养殖区域',
                'verbose_name_plural': '养殖区域',
                'db_table': 'livestock_area',
            },
        ),
        migrations.CreateModel(
            name='LivestockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标标识')),
            ],
            options={
                'verbose_name': '牲畜分类',
                'verbose_name_plural': '牲畜分类',
                'db_table': 'livestock_category',
            },
        ),
        migrations.CreateModel(
            name='LivestockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('quantity', models.IntegerField(default=0, verbose_name='入栏数量')),  # type: ignore
                ('entry_date', models.DateField(verbose_name='入栏日期')),
                ('status', models.CharField(choices=[('active', '养殖中'), ('finished', '已出栏'), ('terminated', '异常终止')], default='active', max_length=20, verbose_name='状态')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.livestockarea', verbose_name='养殖区域')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livestock.livestockcategory', verbose_name='牲畜分类')),
            ],
            options={
                'verbose_name': '牲畜批次',
                'verbose_name_plural': '牲畜批次',
                'db_table': 'livestock_batch',
            },
        ),
    ]
