# Generated by Django 4.2.27 on 2025-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_alter_livestockbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='areas/', verbose_name='区域图片'),
        ),
    ]
