# Generated by Django 4.2.27 on 2025-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_livestockarea_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='livestockarea',
            name='capacity_unit',
            field=models.CharField(default='头', max_length=10, verbose_name='容纳单位'),
        ),
    ]
