# Generated by Django 4.2.27 on 2025-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_remove_livestockcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockarea',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='区域面积(㎡)'),
        ),
        migrations.AddField(
            model_name='livestockarea',
            name='breeding_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='养殖类型'),
        ),
        migrations.AddField(
            model_name='livestockarea',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='位置坐标'),
        ),
    ]
