# Generated by Django 4.2.27 on 2025-12-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_livestockarea_area_size_livestockarea_breeding_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockcategory',
            name='description',
        ),
    ]
