# Generated by Django 4.2.27 on 2025-12-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_remove_livestockcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockbatch',
            name='area',
        ),
        migrations.DeleteModel(
            name='LivestockArea',
        ),
    ]
