# Generated by Django 4.2.27 on 2025-12-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role'),
        ('livestock', '0008_remove_livestockbatch_area_delete_livestockarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('location_code', models.CharField(max_length=50, verbose_name='区域编号')),
                ('capacity', models.IntegerField(default=0, verbose_name='容纳规模')),  # type: ignore
                ('capacity_unit', models.CharField(default='头', max_length=10, verbose_name='容纳单位')),
                ('area_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='区域面积(㎡)')),  # type: ignore
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置坐标')),
                ('breeding_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='养殖类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='areas/', verbose_name='区域图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='区域描述')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='users.farmerprofile', verbose_name='所属养殖户')),
            ],
            options={
                'verbose_name': '养殖区域',
                'verbose_name_plural': '养殖区域',
                'db_table': 'livestock_area',
            },
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.livestockarea', verbose_name='养殖区域'),
        ),
    ]
