# Generated by Django 4.2.27 on 2025-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_livestockarea_livestockbatch_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
