# Generated by Django 4.2.27 on 2025-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_livestockcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockcategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='分类编号'),
        ),
    ]
