# Generated by Django 4.2.27 on 2025-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_livestockcategory_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockarea',
            name='location_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='区域编号'),
        ),
    ]
