# Generated by Django 4.2.27 on 2025-12-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0012_alter_livestockarea_location_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockarea',
            name='area_size',
        ),
        migrations.RemoveField(
            model_name='livestockarea',
            name='breeding_type',
        ),
        migrations.RemoveField(
            model_name='livestockarea',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='livestockarea',
            name='capacity_unit',
        ),
        migrations.RemoveField(
            model_name='livestockarea',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='livestockarea',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='livestockcategory',
            name='category_code',
        ),
        migrations.AlterField(
            model_name='livestockarea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='区域介绍'),
        ),
    ]
