# Generated by Django 4.2.27 on 2025-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_remove_livestockarea_area_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockbatch',
            name='status',
            field=models.CharField(choices=[('active', '养殖中'), ('finished', '已出栏')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
    ]
