# Generated by Django 4.2.27 on 2025-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_alter_livestockbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockbatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='batches/', verbose_name='牲畜图片'),
        ),
    ]
