# Generated by Django 4.2.27 on 2025-12-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_livestockbatch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockbatch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.livestockcategory', verbose_name='牲畜分类'),
        ),
    ]
