# Generated by Django 4.2.27 on 2025-12-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0016_alter_livestockbatch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockbatch',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='breed',
            field=models.CharField(default='', max_length=100, verbose_name='牲畜品种'),
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='gender',
            field=models.CharField(default='混养', max_length=20, verbose_name='牲畜性别'),
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='牲畜简介'),
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='livestock_type',
            field=models.CharField(default='', max_length=50, verbose_name='牲畜种类'),
        ),
        migrations.AddField(
            model_name='livestockbatch',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='牲畜名称'),
        ),
        migrations.AlterField(
            model_name='livestockbatch',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='入栏日期'),
        ),
        migrations.AlterField(
            model_name='livestockbatch',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='养殖数量'),  # type: ignore
        ),
        migrations.AlterField(
            model_name='livestockbatch',
            name='status',
            field=models.CharField(choices=[('active', '在养'), ('finished', '已出栏')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
    ]
