# Generated by Django 4.2.27 on 2025-12-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_livestockbatch_birth_date_livestockbatch_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockbatch',
            name='birth_date',
        ),
    ]
