# Generated by Django 4.2.27 on 2025-12-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0018_remove_livestockbatch_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockbatch',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livestock.livestockarea', verbose_name='养殖区域'),
        ),
    ]
