# Generated by Django 4.2.27 on 2025-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0019_alter_livestockbatch_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestockcategory',
            options={'verbose_name': '牲畜大类', 'verbose_name_plural': '牲畜大类'},
        ),
        migrations.AddField(
            model_name='livestockcategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='分类代码'),
        ),
        migrations.AddField(
            model_name='livestockcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='livestockcategory',
            name='standard_cycle',
            field=models.IntegerField(default=0, help_text='该大类品种从入栏到出栏的预计天数', verbose_name='标准生长周期(天)'),  # type: ignore
        ),
        migrations.AlterField(
            model_name='livestockcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='大类名称'),
        ),
    ]
