# Generated by Django 4.2.27 on 2025-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0021_alter_livestockbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockbatch',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='出栏日期'),
        ),
    ]
