# Generated by Django 4.2.27 on 2026-01-01

from django.db import migrations


def _normalize_category_name(name: str):
    if not name:
        return None

    stripped = str(name).strip()
    if '鸡' in stripped:
        return '鸡'
    if '鸭' in stripped:
        return '鸭'
    if '鹅' in stripped:
        return '鹅'
    if '牛' in stripped:
        return '牛'
    if '羊' in stripped:
        return '羊'
    if '猪' in stripped:
        return '猪'
    return None


def fix_livestock_categories(apps, schema_editor):
    livestock_category = apps.get_model('livestock', 'LivestockCategory')
    livestock_batch = apps.get_model('livestock', 'LivestockBatch')

    target_categories = [
        ('鸡', 'A'),
        ('鸭', 'B'),
        ('鹅', 'C'),
        ('牛', 'D'),
        ('羊', 'E'),
        ('猪', 'F'),
    ]
    target_code_by_name = {name: code for name, code in target_categories}

    all_categories = list(livestock_category.objects.all())

    for cat in all_categories:
        if cat.category_code is not None:
            cat.category_code = None
            cat.save(update_fields=['category_code'])

    candidates_by_target = {name: [] for name, _ in target_categories}
    other_categories = []
    for cat in all_categories:
        target_name = _normalize_category_name(getattr(cat, 'name', '') or '')
        if target_name in candidates_by_target:
            candidates_by_target[target_name].append(cat)
        else:
            other_categories.append(cat)

    canonical_by_target = {}
    for target_name, _target_code in target_categories:
        candidates = candidates_by_target.get(target_name) or []
        exact_match = [c for c in candidates if (getattr(c, 'name', '') or '').strip() == target_name]
        chosen = None
        if exact_match:
            chosen = sorted(exact_match, key=lambda c: c.id)[0]
        elif candidates:
            chosen = sorted(candidates, key=lambda c: c.id)[0]

        if chosen is None:
            chosen = livestock_category.objects.create(
                name=target_name,
                category_code=target_code_by_name[target_name],
                description=None,
                standard_cycle=0,
            )
        canonical_by_target[target_name] = chosen

    for target_name, canonical in canonical_by_target.items():
        expected_code = target_code_by_name[target_name]
        need_update_fields = []
        if (getattr(canonical, 'name', '') or '').strip() != target_name:
            canonical.name = target_name
            need_update_fields.append('name')
        if (getattr(canonical, 'category_code', None) or '').strip() != expected_code:
            canonical.category_code = expected_code
            need_update_fields.append('category_code')
        if need_update_fields:
            canonical.save(update_fields=need_update_fields)

    for target_name, candidates in candidates_by_target.items():
        canonical = canonical_by_target[target_name]
        for cat in candidates:
            if cat.id == canonical.id:
                continue
            livestock_batch.objects.filter(category_id=cat.id).update(category_id=canonical.id)
            cat.delete()

    for cat in other_categories:
        livestock_batch.objects.filter(category_id=cat.id).update(category_id=None)
        cat.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0022_livestockbatch_finish_date'),
    ]

    operations = [
        migrations.RunPython(fix_livestock_categories, migrations.RunPython.noop),
    ]

