# Generated by Django 4.2.27 on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0023_fix_livestockcategory_fixed_six'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockbatch',
            old_name='entry_date',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='livestockbatch',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]

