# Generated by Django 4.2.27 on 2026-01-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0024_rename_livestockbatch_entry_date_to_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockbatch',
            name='name',
        ),
    ]
