# Generated by Django 4.2.27 on 2025-12-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0019_alter_livestockbatch_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='溯源码')),
                ('query_count', models.PositiveIntegerField(default=0, verbose_name='查询次数')),  # type: ignore
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),  # type: ignore
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trace_record', to='livestock.livestockbatch', verbose_name='养殖批次')),
            ],
            options={
                'verbose_name': '质量溯源',
                'verbose_name_plural': '质量溯源',
                'ordering': ['-created_at'],
            },
        ),
    ]
