# Generated by Django 4.2.27 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability_app', '0002_remove_livestocktrace_query_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestocktrace',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='trace_qr_codes/', verbose_name='溯源二维码'),
        ),
    ]

