# Generated by Django 4.2.27 on 2025-12-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_operationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
