# Generated by Django 4.2.27 on 2025-12-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_adminprofile_avatar_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationLog',
        ),
    ]
