# Generated by Django 4.2.27 on 2025-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_operationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='business_license',
        ),
        migrations.AddField(
            model_name='certification',
            name='breeding_license',
            field=models.ImageField(blank=True, null=True, upload_to='certs/licenses/', verbose_name='养殖许可证'),
        ),
        migrations.AddField(
            model_name='certification',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='certification',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='certs/id_cards/', verbose_name='身份证反面'),
        ),
    ]
