# Generated by Django 4.2.27 on 2025-12-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_certification_business_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
