# Generated by Django 4.2.27 on 2025-12-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='id_card',
            field=models.CharField(max_length=255, verbose_name='身份证号'),
        ),
    ]
