# Generated by Django 4.2.27 on 2025-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_certification_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号'),
        ),
    ]
