# Generated by Django 4.2.27 on 2026-01-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vetprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VetProfile',
        ),
    ]
